# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: todo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntodo.proto\x12\x04todo\"6\n\x04Todo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"7\n\x11\x43reateTodoRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\".\n\x12\x43reateTodoResponse\x12\x18\n\x04todo\x18\x01 \x01(\x0b\x32\n.todo.Todo\"\x1c\n\x0eGetTodoRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"+\n\x0fGetTodoResponse\x12\x18\n\x04todo\x18\x01 \x01(\x0b\x32\n.todo.Todo\"-\n\x11UpdateTodoRequest\x12\x18\n\x04todo\x18\x01 \x01(\x0b\x32\n.todo.Todo\".\n\x12UpdateTodoResponse\x12\x18\n\x04todo\x18\x01 \x01(\x0b\x32\n.todo.Todo\"\x1f\n\x11\x44\x65leteTodoRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"%\n\x12\x44\x65leteTodoResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x90\x02\n\x0bTodoService\x12\x41\n\nCreateTodo\x12\x17.todo.CreateTodoRequest\x1a\x18.todo.CreateTodoResponse\"\x00\x12\x38\n\x07GetTodo\x12\x14.todo.GetTodoRequest\x1a\x15.todo.GetTodoResponse\"\x00\x12\x41\n\nUpdateTodo\x12\x17.todo.UpdateTodoRequest\x1a\x18.todo.UpdateTodoResponse\"\x00\x12\x41\n\nDeleteTodo\x12\x17.todo.DeleteTodoRequest\x1a\x18.todo.DeleteTodoResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'todo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TODO._serialized_start=20
  _TODO._serialized_end=74
  _CREATETODOREQUEST._serialized_start=76
  _CREATETODOREQUEST._serialized_end=131
  _CREATETODORESPONSE._serialized_start=133
  _CREATETODORESPONSE._serialized_end=179
  _GETTODOREQUEST._serialized_start=181
  _GETTODOREQUEST._serialized_end=209
  _GETTODORESPONSE._serialized_start=211
  _GETTODORESPONSE._serialized_end=254
  _UPDATETODOREQUEST._serialized_start=256
  _UPDATETODOREQUEST._serialized_end=301
  _UPDATETODORESPONSE._serialized_start=303
  _UPDATETODORESPONSE._serialized_end=349
  _DELETETODOREQUEST._serialized_start=351
  _DELETETODOREQUEST._serialized_end=382
  _DELETETODORESPONSE._serialized_start=384
  _DELETETODORESPONSE._serialized_end=421
  _TODOSERVICE._serialized_start=424
  _TODOSERVICE._serialized_end=696
# @@protoc_insertion_point(module_scope)
